-- Feather Framework clean-install catalog seed.

INSERT INTO `categories` (`id`, `name`) VALUES
    (1, 'uncategorized'),
    (2, 'ammunition'),
    (3, 'weapons'),
    (4, 'provisions'),
    (5, 'medicine'),
    (6, 'materials'),
    (7, 'valuables'),
    (8, 'tools'),
    (9, 'clothing'),
    (10, 'documents')
ON DUPLICATE KEY UPDATE `name` = VALUES(`name`);

INSERT INTO `items`
    (`name`, `display_name`, `description`, `max_quantity`, `max_stack_size`,
     `weight`, `usable`, `category_id`, `type`, `instance_mode`)
VALUES
    ('consumable_apple', 'Apple', 'A tasty apple.', 100, 20, 1.00, 1, 4, 'item_item', 'stack'),
    ('water_bottle_small', 'Small Water', 'A small bottle of water.', 100, 1, 2.00, 1, 4, 'item_item', 'unique'),
    ('weapon_pistol_volcanic', 'Volcanic Pistol', 'Volcanic Pistol.', 20, 1, 2.00, 1, 3, 'item_weapon', 'unique'),
    ('weapon_pistol_m1899', 'M1899 Pistol', 'M1899 Pistol.', 20, 1, 2.00, 1, 3, 'item_weapon', 'unique'),
    ('weapon_pistol_semiauto', 'Semi-Automatic Pistol', 'Semi-Automatic Pistol.', 20, 1, 2.00, 1, 3, 'item_weapon', 'unique'),
    ('weapon_pistol_mauser', 'Mauser Pistol', 'Mauser Pistol.', 20, 1, 2.00, 1, 3, 'item_weapon', 'unique'),
    ('weapon_revolver_doubleaction', 'Double-Action Revolver', 'Double-Action Revolver.', 20, 1, 2.00, 1, 3, 'item_weapon', 'unique'),
    ('weapon_revolver_lemat', 'LeMat Revolver', 'LeMat Revolver.', 20, 1, 2.00, 1, 3, 'item_weapon', 'unique'),
    ('weapon_revolver_navy', 'Navy Revolver', 'Navy Revolver.', 20, 1, 2.00, 1, 3, 'item_weapon', 'unique'),
    ('weapon_repeater_carbine', 'Carbine Repeater', 'Carbine Repeater.', 20, 1, 2.00, 1, 3, 'item_weapon', 'unique'),
    ('weapon_repeater_lancaster', 'Lancaster Repeater', 'Lancaster Repeater.', 20, 1, 2.00, 1, 3, 'item_weapon', 'unique'),
    ('weapon_repeater_henry', 'Litchfield Repeater', 'Litchfield Repeater.', 20, 1, 2.00, 1, 3, 'item_weapon', 'unique'),
    ('weapon_repeater_evans', 'Evans Repeater', 'Evans Repeater.', 20, 1, 2.00, 1, 3, 'item_weapon', 'unique'),
    ('weapon_rifle_springfield', 'Springfield Rifle', 'Springfield Rifle.', 20, 1, 2.00, 1, 3, 'item_weapon', 'unique'),
    ('weapon_rifle_boltaction', 'Bolt Action Rifle', 'Bolt Action Rifle.', 20, 1, 2.00, 1, 3, 'item_weapon', 'unique'),
    ('weapon_rifle_varmint', 'Varmint Rifle', 'Varmint Rifle.', 20, 1, 2.00, 1, 3, 'item_weapon', 'unique'),
    ('weapon_sniperrifle_rollingblock', 'Rolling Block Rifle', 'Rolling Block Rifle.', 20, 1, 2.00, 1, 3, 'item_weapon', 'unique'),
    ('weapon_sniperrifle_carcano', 'Carcano Rifle', 'Carcano Rifle.', 20, 1, 2.00, 1, 3, 'item_weapon', 'unique'),
    ('weapon_rifle_elephant', 'Elephant Rifle', 'Elephant Rifle.', 20, 1, 2.00, 1, 3, 'item_weapon', 'unique'),
    ('weapon_shotgun_doublebarrel', 'Double-Barreled Shotgun', 'Double-Barreled Shotgun.', 20, 1, 2.00, 1, 3, 'item_weapon', 'unique'),
    ('weapon_shotgun_sawedoff', 'Sawed-Off Shotgun', 'Sawed-Off Shotgun.', 20, 1, 2.00, 1, 3, 'item_weapon', 'unique'),
    ('weapon_shotgun_pump', 'Pump-Action Shotgun', 'Pump-Action Shotgun.', 20, 1, 2.00, 1, 3, 'item_weapon', 'unique'),
    ('weapon_shotgun_semiauto', 'Semi-Auto Shotgun', 'Semi-Auto Shotgun.', 20, 1, 2.00, 1, 3, 'item_weapon', 'unique'),
    ('weapon_shotgun_repeating', 'Repeating Shotgun', 'Repeating Shotgun.', 20, 1, 2.00, 1, 3, 'item_weapon', 'unique'),
    ('weapon_revolver_cattleman', 'Cattleman Revolver', 'A standard single-action revolver.', 20, 1, 2.00, 1, 3, 'item_weapon', 'unique'),
    ('weapon_revolver_schofield', 'Schofield Revolver', 'A sturdy top-break revolver.', 20, 1, 2.00, 1, 3, 'item_weapon', 'unique'),
    ('ammo_rifle_elephant', 'Rifle Cartridges - Nitro Express', 'Nitro Express cartridges for the Elephant Rifle.', 200, 50, 0.00, 1, 2, 'item_ammo', 'stack'),
    ('ammo_pistol_regular', 'Pistol Cartridges - Regular', 'Regular cartridges for pistols.', 200, 50, 0.00, 1, 2, 'item_ammo', 'stack'),
    ('ammo_pistol_express', 'Pistol Cartridges - Express', 'Express cartridges for pistols.', 200, 50, 0.00, 1, 2, 'item_ammo', 'stack'),
    ('ammo_pistol_high_velocity', 'Pistol Cartridges - High Velocity', 'High velocity cartridges for pistols.', 200, 50, 0.00, 1, 2, 'item_ammo', 'stack'),
    ('ammo_pistol_split_point', 'Pistol Cartridges - Split Point', 'Split point cartridges for pistols.', 200, 50, 0.00, 1, 2, 'item_ammo', 'stack'),
    ('ammo_pistol_explosive', 'Pistol Cartridges - Explosive', 'Explosive cartridges for pistols.', 200, 50, 0.00, 1, 2, 'item_ammo', 'stack'),
    ('ammo_revolver_regular', 'Revolver Cartridges - Regular', 'Regular cartridges for revolvers.', 200, 50, 0.00, 1, 2, 'item_ammo', 'stack'),
    ('ammo_revolver_express', 'Revolver Cartridges - Express', 'Express cartridges for revolvers.', 200, 50, 0.00, 1, 2, 'item_ammo', 'stack'),
    ('ammo_revolver_high_velocity', 'Revolver Cartridges - High Velocity', 'High velocity cartridges for revolvers.', 200, 50, 0.00, 1, 2, 'item_ammo', 'stack'),
    ('ammo_revolver_split_point', 'Revolver Cartridges - Split Point', 'Split point cartridges for revolvers.', 200, 50, 0.00, 1, 2, 'item_ammo', 'stack'),
    ('ammo_revolver_explosive', 'Revolver Cartridges - Explosive', 'Explosive cartridges for revolvers.', 200, 50, 0.00, 1, 2, 'item_ammo', 'stack'),
    ('ammo_repeater_regular', 'Repeater Cartridges - Regular', 'Regular cartridges for repeaters.', 200, 50, 0.00, 1, 2, 'item_ammo', 'stack'),
    ('ammo_repeater_express', 'Repeater Cartridges - Express', 'Express cartridges for repeaters.', 200, 50, 0.00, 1, 2, 'item_ammo', 'stack'),
    ('ammo_repeater_high_velocity', 'Repeater Cartridges - High Velocity', 'High velocity cartridges for repeaters.', 200, 50, 0.00, 1, 2, 'item_ammo', 'stack'),
    ('ammo_repeater_split_point', 'Repeater Cartridges - Split Point', 'Split point cartridges for repeaters.', 200, 50, 0.00, 1, 2, 'item_ammo', 'stack'),
    ('ammo_repeater_explosive', 'Repeater Cartridges - Explosive', 'Explosive cartridges for repeaters.', 200, 50, 0.00, 1, 2, 'item_ammo', 'stack'),
    ('ammo_rifle_regular', 'Rifle Cartridges - Regular', 'Regular cartridges for rifles.', 200, 50, 0.00, 1, 2, 'item_ammo', 'stack'),
    ('ammo_rifle_express', 'Rifle Cartridges - Express', 'Express cartridges for rifles.', 200, 50, 0.00, 1, 2, 'item_ammo', 'stack'),
    ('ammo_rifle_high_velocity', 'Rifle Cartridges - High Velocity', 'High velocity cartridges for rifles.', 200, 50, 0.00, 1, 2, 'item_ammo', 'stack'),
    ('ammo_rifle_split_point', 'Rifle Cartridges - Split Point', 'Split point cartridges for rifles.', 200, 50, 0.00, 1, 2, 'item_ammo', 'stack'),
    ('ammo_rifle_explosive', 'Rifle Cartridges - Explosive', 'Explosive cartridges for rifles.', 200, 50, 0.00, 1, 2, 'item_ammo', 'stack'),
    ('ammo_shotgun_regular', 'Shotgun - Regular', 'Regular shells for shotguns.', 200, 50, 0.00, 1, 2, 'item_ammo', 'stack'),
    ('ammo_shotgun_slug', 'Shotgun - Slug', 'Slug shells for shotguns.', 200, 50, 0.00, 1, 2, 'item_ammo', 'stack'),
    ('ammo_shotgun_buckshot_incendiary', 'Shotgun - Incendiary', 'Incendiary buckshot shells for shotguns.', 200, 50, 0.00, 1, 2, 'item_ammo', 'stack'),
    ('ammo_shotgun_slug_explosive', 'Shotgun - Explosive', 'Explosive slug shells for shotguns.', 200, 50, 0.00, 1, 2, 'item_ammo', 'stack'),
    ('ammo_varmint', 'Rifle Cartridges - Varmint', 'Regular .22 caliber cartridges for varmint rifles.', 200, 50, 0.00, 1, 2, 'item_ammo', 'stack'),
    ('ammo_varmint_tranquilizer', 'Rifle Cartridges - Tranquilizer', 'Tranquilizer cartridges for varmint rifles.', 200, 50, 0.00, 1, 2, 'item_ammo', 'stack'),
    ('gun_oil', 'Gun Oil', 'Gun oil used to clean and restore weapon condition.', 20, 10, 1.00, 1, 8, 'item_item', 'stack'),
    ('cattleman_long_barrel', 'Cattleman Long Barrel', 'A long barrel made for the Cattleman Revolver.', 20, 10, 1.00, 0, 3, 'item_item', 'stack')
ON DUPLICATE KEY UPDATE
    `display_name` = VALUES(`display_name`),
    `description` = VALUES(`description`),
    `max_quantity` = VALUES(`max_quantity`),
    `max_stack_size` = VALUES(`max_stack_size`),
    `weight` = VALUES(`weight`),
    `usable` = VALUES(`usable`),
    `category_id` = VALUES(`category_id`),
    `type` = VALUES(`type`),
    `instance_mode` = VALUES(`instance_mode`);
